---
apiVersion: v1
kind: Namespace
metadata:
  name: assignment3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: assignment3
  name: deployment-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-nginx
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-nginx
    spec:
      containers:
      - image: nginxdemos/hello:latest
        imagePullPolicy: Always
        name: app-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: assignment3
  name: service-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: assignment3
  name: deployment-survey
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-survey
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-survey
    spec:
      containers:
      - image: romple/swe645-assignment2:latest
        imagePullPolicy: Always
        name: app-survey
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: assignment3
  name: service-survey
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-survey
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: assignment3
  name: ingress-nginx
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: assignment3.rompledev.com # give your domain name here
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /nginx
          pathType: Prefix
          backend:
            service:
              name: service-nginx
              port:
                number: 80
    - http:
        paths:
        - path: /survey
          pathType: Prefix
          backend:
            service:
              name: service-survey
              port:
                number: 80
