apiVersion: v1
kind: Service
metadata:  
  labels:
    app: mytomcatdeployment
  name: mytomcatdeployment  
spec:
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 8080    
    targetPort: 8080
  selector:
    app: mytomcatdeployment